pico-8 cartridge // http://www.pico-8.com
version 32
__lua__
--it's a feature (drippy sort)
--alexthescott
--8/24/21

p={8,136,130,11,139,131,12,140,129}
pal(p,1)
c=1

function burn()
	for p=0,2024do
		x=rnd(128)
		y=rnd(128)
		pc=pget(x,y)
		if (p-1)%3!=0 then
			--holding a magnet to 
			--a old computer type-beat? 
			pset(x,y+2,pc-1)
		end
	end
end

function add_brush()
	local b={}
	
	b.c=c
	b.x=0
	b.y=rnd(2)\1
	b.v=1
	
	b.update=function(slf)
	 slf.x+=slf.v
	end
	
	b.set_c=function(slf,c)
		slf.c=c
	end
	
	b.draw=function(slf)
		pset(slf.x,slf.y,slf.c)
	end
	
	b.destroy=function(slf)
		if slf.x>=128 then
			del(brushes,slf)
		end
	end
	
	add(brushes,b)
end

brushes={}
add_brush()

cls()
::♥::
if t()<2 then
	print("it's a feature",36,64,1)
else
	--burn() is our unexpected effect
	burn()
	
	if t()%3==0 then
		add_brush()
	end
	
	if t()%6==0 then
		for b in all(brushes) do
			b:set_c(c)
		end
		c+=3
		c%=10
	end
	
	for b in all(brushes) do
		b:draw()
		b:update()
		b:destroy()
	end
end

flip()
goto ♥
__gfx__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888800000000000000000000000000000000000000
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0fffffffffffffffffffffffffffff
000000000000000000000000000000000000000000000000000000000f000000000000000f000f00f00ff00fffffffffffffffffffffffffffffffffffffffff
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefeeeeeeeeeeeeeeeeeeefeeeeeeeee
ffffffffffffffffffffffffffffffffffffffffffffffffffeffeefeefffffffefeeefeeeefeefeeeefefeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ddddddeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeddddddddddddddddddddedddddddddddddddddddeddddddddd
eeeeeeeeeeeeeeeeeeedeeeeeeeeeeeeeededeeeeeeedeeeeededddddddededdeddddddddddedddddddefddddddddddddddddddddddddddddddddddddddddddd
fccccddcccccccccecccccccccccccccccccccccccccecccccccccccccccccccfcccdccccccccdcccccdfcccccccccccccdcccccccccccccccccccdccccccccc
dddddddddddddddddddcddddddddddddcccdccddcdcdcccdddcdcccccccccdcccccccccccccdcccccccdeccccccccccccccccccccccceccccccccccccccccccc
edbbbcebdbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbccebbddbbbbbebcbcbbbbbbbbcbbbbbcebbcbbbbbbbbbbcbbbbbbbbbbbbbbbbbcbcbbbbbbfeb
ccccccccccccccbccccbccccccccbcccbebcbbccbbbcbbbbbcbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbcbbcdbbcbbbbbbdbbbbdbbbbbcbbdbbbbcbbbdbbbbbbbbbb
dcaabbdacbaaaaafcaaaaaaaaaabaaaaadcaaaacaaaacaaaaaaadcdaaccaaaaadababaaaacadabbaaaabdaabbbaaaaaaaabacaaaaacaaaaaaaaababaaaaaaeda
bbbbbbdbbbbbbbabbbbaabbbcdbbababadabaabcaaabaaaaaacaaaaaccccaaaacaaaaaaaacaaaaaabaabcaabcaaaaacaaaacaaababaadaababaaacaadadaaaaa
cbhhaachbahhhhhebbhhhhehhhbahehbecbhhhhbhhhhbhhchbahcbchfbbhhhahchahahbhhbhchaahbhaachheaahhhhhhhbehbhhhhhbhahhchhhhahahahhhhdcb
aaaaadcaacaaaaaaaaaheaaabcahdaadhchaahhbcdhahhhhhhbhhhhhbbbehhhhbhhhhhhhdbahhhhaaahafhhabhhhhhbhhhhbhhhahabhchhahahhhbhhchchhhhh
basshhbhahsssasdaabssadsssahsdsadbassssasscsaasbsacsbabseaahsshsbshsbsassasbbhasaschbssdhhsbsssbsadsaaabsaashssbsssshsbbhhscacba
chchhcbhbbhhddhhhhhhdbhhabhachhcsbshhseabcssbsssssassssaaaadssssassssasbcabssscdhhshessbasssssabbssahsshshaabsshshsssacsbsbssaes
ahccbsashsccchcchhabshchcchshcbhcahcccchccbchhcachbcahacdhhscacbacaeachcchsaashchcbsaaccsscacccachcbhhhachccschaccecacaasscbhbah
bsbssbabaasbccssshsscaschashbssbcaccccdhabcbacchcchchcchhhhccccchsccchaabhacccbcssbsdcdahcaccchaacccaccscshhadashbccchbddcacshdc
hbjjachcscdjjcsbscaacsbscbscsbasbhsjebjsbjajssjbbsabhshjcsscjhbahbhdhjsjhbhhhbshsaachhsbcbbhbjjhjseassshjabccjshjjdjhchhccdacaas
acacaahahhcabbcccsccbbcjshsbacsajhbjbacshahahjjsjasjshjscssbjaccscjjjshhasbdjjcfccaccccdsjhcjjshhbjbhjbcjdsshchcsacajsaccjajcsdj
sacrhjsjcjcrrbcacbhdjdacaacjcahcaccrdabcarhrcchaahhascsrbchcrsahsbscsrcasasesacschhacscajaasarrsrcdhcccschabjrcbrcccsbbsjdchbhha
hjdahhshcsjhaaacjcbjaarrcscahjchrsahahbcshchsrdcahcrcsrcbccarhjbbabrrcsshcacrrbebbhbbbbccrsjrccssarasrajrcccsbcechbhrchbbahceccr
chjbsreajddbfajdhaschchjhhjrdhcjabjbchbjhssbjjshhssbcjcbajsbbchshccbcbbhchcdcfjcjsshbchbrhhchbbcbccsjbjcbbhardjabjbccbacrcbsassh
hrchsscbbcrbhhhjcjarhhbcjcchsrcsbchshceccsbadbcjhsjbacbjacjhfsraahabbdccsjhbabadaasaaaabjbcrbbjcchbhchhrsbjjcabdjsascjsbahsbdcbb
jsriccdhbccrehccshcbsbsbssrscsbbharjbsarsccerrcssch0jrjahrcahescsbcajiasjsjccebbrccsajsabesbshijdabcbarjaashbchhirabjahcbbachdds
sbbsccbaajaaassrbahbssijsjbsbbbeijscabdbdcahccbrscdihairhbrsecbhhshbacbbcrdahhhchhhhhhharidbbabcasisjssdcarrchaccshcbrcahscacjai
hcbhhbcsabbbdsbbcsjacacaccccbseashbrachbcjjdshjchjsfcbrhsdjhsdcjcajhcshchcrbbdaahabchrbhddcacsorchajahbrhdcaibssocharcsjeaeasccc
ciacajahhbhhhbcsa0siccorcracaaadarahdacacjhsb0abbjcoshobhaecdbisscsahbaajcchssebssssbsshbociahajhcccrcccjhhsjshbbcscaajhccjhbrhc
sjissabchaaiccaajchhjhjhjjbjacdhcsibhjsihrcccsrjsrdedhbsaccsccbbjhrsbcbbsjbaachhshajsbdcccjhhcadbbhrhsacccjhcaccabshbbhrdhdbcbbj
hohjhbhssacsscjchfhsdj8bjchchhhchahschbhbdcaafhiarb8cs8ishdjcaoccjchcachrbbsccdaccbcaccbahbohshrsjbjbjjbcbccbcsaahcbhhcebjrsabsb
ccocchacshhobjhccjssrsrsrcarhjcsjcorsrfobbjbjcbccbcdcsiahbjcjbaahsbcajaacrdadbsscshrhrcbbbrssjhcaasbschbbbbsjhb0hacsiasbcscajaar
sssrsasachbccbrjsesccd0arbsjsssbshdcbsasacbhhedohba0jc0bcscreh8djrcsbbbshbacjjchjcajhjjahsa8scsbdrariraajabaajchhsfassedarbchica
jb8jjshbcsaharsbbrccchccbjhbdrbcbb8jcse8aircrjibjcbcbcbhsahjrahhscijhrhhjechcaccbdsbsbbaaaccccsbhahiccaaaaacrsafchjcohhidcbhshcb
sccbchbhjhabjabrcdcjbcfhbabrcccahscjachcdbassdfssihfrjiaecbbds0crbbbaaassahbsrbsrbhrsrrcschccjsicchsachhrhahhrjssfehccdchbijsssd
ra0rrcsajchshbhaabjsbacjsrchcaaaaadcjcdahobbhroardcbabaschscbhdscjorsbasrdbsbhjjacaicaahhhcjjbcashsdjbhhhhhjechebsrj8sshcjascsbi
cjjijsashsbarcibccerabcsihabjjbhscbrhjsjcahcccecccssbrhhddaiccfbbbaahhccbdsacbasbaabcacbajfbjrchbbschssscshsscraaedsjscbsbdrcbcc
bhfbbachrjscaishhircahbrcbdcbahhhhcbrjchseiascchbcbahahcbccdicccjr8bcihcbcacassccbhoahhhsbbrrajhcsccbasssssedssdacbr0ccsbchcbcab
jchorchbscahbbsabbdbhbbabdhahrascjaasrcrbhsjjbdjhbccbbsscchodbeaaahbssbdacchjihcihcishbahreahajsaacjscccbcschjbhheccrcbaeicbjajb
isaiihjsjecjbohssabjdsabjicbchssssbabrbscdohcjbssbahshsjabjchbbjhbabjbsjibhehccbbfssbdescaahbhrsjbjbahhccccdcccchjhcfjefajsjaaha
bbs8bjsacjhsiachcaccsaahacshsahcjrhhccesascrbacrsajcaihcbbsscaehhhaacbachbbsrosjosbhcsahsbdhbhrchhjrccabajbjsrissdbjdjahdsbirhra
achaoshdrdjha8scchirccchsobabscccsahccacecdsjracaahscscrhcbbcaarbihihacraasdsjcaaeccacecbhhsisbcrarahssjjhbcbcc0srsbecdehrcrhhsh
aac0fhchjrscohjsbcbbchhshbcschsbrrbbbjdchcjfahbbchrbhosbaaccbhdssshhcahbsaacbsbrbcafhchscscsashssscbbbhahcarbaocacarcrhsccadbsca
hjcd8cscbcrbhhbcjcjbbjbsc8ahacbjbchsbbhjdbccbhhjhhscbcjbsbaabhhbacccsajbhhbcahbhhdbjhbdjasscochhchdcsccsrsabbbbfcbcacbcdsjjbsscs
hhchesjdrccj8eraabcajsscaajcjscabbaaarcjsjrehsabjsbashcaahjjasccccbbbhsacehjacabaehesjsdjbbhhcscccbraahhdbhbah8jhbhabbsabacciejh
srbc0hcbbbeassabrbsiaracj0hsbearajscaasccabjassssscjacrbcaehaccchjbbchrbscabhsasscarsacahcccaassbscbcejcbchaaaaejijhjacccrjbscsh
ssbsdcrcdbcrbdbhaabhhccjhhrjrhjhbihhccbrcacdccharcihcsjhhsrrhcbjejaaaschhdshhjhdhdsdcrscraassjbjjaabhhcscasihs0rsashaachahbbodra
aaabfsbaaadhbchabacohachbfscadhehrceehajbharhccccfjrhbaahhdshbbesaaajshaabhcschccbebchbhsjjbhhccacbasdrccjshhhhdrcrschbbjbracbcs
ccaccjbbcabbccishhascjjdsshrbsrbasssbbaajhjcbbahjbosjcbbacbbsjardrhhccjsscbasdscccdcjbcbahcccracrhcissbcbhcoscsachcsbdbshbaa8cbh
hhhaabdhhhcsajahihj8shbsaecjhccdsbhddshaashasjjjjecssahhshccseadchhhrcshhasbajsjeadibcadcrhasajchdahccbbjcdsssscbjbbjcaaribhbajc
bjhjbrhabcaibbccsaccbrrcccsbicbahcccaahhrsrbaahsraaccbaahjiicrhbcbssbcrccbahccdbbbcbrijahsbjjbhjcsbocbajasjdbacbjhbcacacsahhcbis
ssshhacsssbahbhssarcasachcjrsbbdcbscccshhcbhbrrhrdbcahsscsbaadhcjsbcbjcsshcahrchdhcbabhcjbshccrbscassbhasbcccccbisiacbhhboisabrs
arcrajshabhhaabcchbfabsbjjcbdjahcjsjhhssedbahescb0hjjahhchohjsabbscbabbjjahsjbcababecorhscarrhsrbbdchahafcrcahjahsaahbhjchcajaos
cbcsshbfccadsascchcbhdhjsjrbcaacjacbdachsbdsabbdacabhscejcahhcsbaaabirjccsjbsrhscsbiaasbrscsjbbaabhccashcabjjhhaobhhbassa8cchabc
hcbbhrcdhasshaabjsaehhccscjdcehsbcccssccdcihsdcjifscrhssbsdsrchaacbaaabcrhschabaahadb8cscjhabssbaacjshsaejbbhsdhschbsbsbjsbhdh8c
jajccsaejahcchdjjejascbbcrbdjhhbchcachjecacchaachbhascjdcjhscbaahbbaccrjacracbscbcaohdcabcjcraihhasjjhchjharrssh8assahach0bjshij
sbaishjcshccshhaachdssjbcbrcbdscabjbccbjcbocccjrhecebsbbddccbjshhcahhhababccshahhshcafjcjashiccchhbraschdrbasccscjsaaaaarcascssj
rhrjjchdrhsbjacrrdrheeaajbicrssabsbhbsbdjhbashhesfbhajacbrshbahhsaahbbjbhjchjbdjabh8scjcasrjbhsashcrrsjsdhhbbcbsbhcshshjsjarcssr
cahrcsrbcbbsccsbhsscccrajabbacccharajharbacbsbsbsdjdicaaccbjsrccbbhssshahajbcshsscsbhercrhcsabjjcsabhcjscbahcjbcjrchhhhhjdhcbccr
csbcrjscbscarhbsbcbsedhhriobbcchacasacacrsahcscdceashrhbaccsahssahhscaracrbsracdhahhcbrbhcbrischcshbbcrccceiibabadccscsdcrhbhccb
hhsbdccajaacjbcasccbjjbhrhiahbbbshbhrsacahbacacbccrcdjhhbbdrbbjbaabcccshshaaacsccacabdhjbsbcharsbchcsjcabahccrajrbjhssssrcsjascb
jchbbrabccjhbsachbbcdca0besaiajshjhchjhbbchsjcbcbdhcsbsahjjchsdchsshbhchbbacccbcchssjabasjbcccjsbcsbijbjbbdooadbacbjcbccjbsisjji
csaicjbhrbdjrcjhcjjarrisbhhhdaaacsaahchbasdhjhjbcbbbccsdaacbacdahhajaecscsbhcdajjhjaacshccajshccajsjhrbhacsbbbhrbcssccccbbbrhcbi
rjsdsbbabjdsiccjsaaccbhfhdchohbcshajcrsahcscsjcbaccjbachbrrjsccjsscsasbsaihjjbabbsccdhahcrabjjrcajcachiraacbchcahbarjdjbcicbcrrs
bchobrasbacrhbasjrrhbbbciseschhccchhsjsahbcsssrabahabjcchhbdhdcdbshrhdjhjbasbchrhsrhhbbsbjhrcsfbhrchsbashbcbacsbijccbjjhiaabsbao
jhccccadasccojbrshhjbasescjs8sajashbbbchsbhjcrbahbbrahjsasbrfabrcajchcacdodrrahaacjecshsjbcabrcbhajhjdobhhbajcbhsfhbrcccjocaabbc
ajssabhcahbasahcedbsiaahscdcbssbbasserchsabccbhhahsbarcbhaacscbcahssscsbbahcacscscbssaacfrsbaceasdjsaahcsajahbccorjjasrsohhhceh8
rsjbjjhdhcbb8rabcscrahcdcbacachrhcsaaahscasrbbahsaabhsrcbcbaehabjhajsjhjc8cbhhshhjrdbcscrcbhabjashaarcbiscahrbasceshbbbbrhbhhaij
hacchisbdsahchsbdcicohhscjcjascaahccdbjdchahsasshscahbbdchhbbbdbhscbcbcaaasjhbcbcjscehhjehbihcdhccrahhsjchrheajj8brrhcbc8sssjdsd
bcrarhecsjaaachbjcbbhsjcjahjhjshsjchhhscchcbaihechejscbjajahdshaaahrcrsrb0bisscasrbcajcjbbesbcbhcshhbbacdbhsbahabdcsaacacsabchor
shjbsscacbhsfscacbcc8hsccreshcjhbsjjcircjhhsccccscjhsiacbssaaacaschajajhhbcrsajcjrcsdasrddashbcbjbbhsshrjsbsdhbr0icbajijjcccrccc
ijbhssdbcrhbcbsarjaibcabrhsbsrcscsjcssaabsjihjsdjbdrbjirhrhbccshhhs0jbcbadaocchhcbjbcrbreadcajasjcsshahjcascihshacjchhbhjchabssb
csraccshbascecjhbabj0sbjbhdcsjrsacbrbabbcsscjbjaajrscaheaccdhhbdcbshbhrssajbchrbrahcchdccchcsababaisccssrcaacsaasojihrorrjjabbbb
sbihcccajbsabachbrhcajhabscdcabcjcrbachhacrhsrdcracbaacbdcsabscssscfrajjbcc8bjsdsjcabhajdhchhrhcajccshsrbhchoscehbrbssdsdjshaccd
jcahjjcsahhjdjrbahasccbsadejcrbahjabahcabdcjradhhcbdbhsdhbbcssbcbacsasacchrcassachsjcscbcbcjchacaaocjjccjjhhbchhc8rrsb8bbrrhbeaa
caosbjbheichahjsbbsbhrshicjcjhajrjbchjbbhcbscbcbbhbiehbicbchacjcccaebhrrabb0arcccrbhabbrcsbsdbsjhbjccscbasjshcjdcahacccccrcshjjc
rehshhjchssrcbbahhhcjjachcdrabihsrhahsbbaccsbhcssbicasccsaabhbabahbhhcabhsbjhcchbcchbcbababcjshbhhajrrajrhssajssjcsecj0hahbsadhh
jehccdasdbcshsrcaicasbcscdhbrbhsacabsraasbacjbbaisaodsaobajshjrjchhfisbbhaafhbcbjbashdabbcacchcrsarfjajihchcsjrcbhshbjbjbcjcsrhb
bdscbsrjsccadaihssbderhjsbcbhchscbsdscaahbbaisbccaobhcjbshhasacahsassjhadbissjjaabjbaaahahabrcaasshrbehrjscddrhcrbcdjrfshsichcss
hdshbchccabdscbjcajhbjccjcsdbaschbhccbhhcahjaaaaach8cch8ahdcshbcbssehcejdhhasibarihcscbicbhabsjschcebahhsbsbcrbbahcsasbrabrjhdsa
acsjacbrcjjhchcsccacdbsrcabisbscjhbcsjhhsaahodaajh8aajracsshchbhsdhhcrchcaocaarhharahhhshshahhhhcbsbhdsbrcjcchsjcajcrbacsbabsbch
sccsabsjbhaccjirbhrsarbjrbccihcjaasbcsdsjhsahhhhhjsabbsahscjcsibacddsjdrcsshcjahbasjcbabbashadacjsjdacsscacabbiahsscccabhachhcch
hbcbhjibjabsbbbcbbbbcicajhabhacjcsabcrssdbhsachhre0hhsbhjcbsjsasccssjbbsbhhjhhasshbbssscscsdsasscacisccibbrbbacrjhrbbihsbchacajs
cbjchacrashbjrobasbchbarbajbosarhhcabdccrachsssssrchaachscbrjccahjcccrcbbchecrhcihcbaahaahashchjrcrchbccjhjhaiohscdjbjccbhjdsbjd
sajasrocrhacaaajaaaabajhrsbashjrbbhacccccasbhbssbddsscasrjachchfjcbcraasassdcshcascdchcacjccchccchjaabjhsabaahjbrbbaboscabsfjhrc
jarjshsbccsarbecacijsibbahba8ahbssjhacbjbhjscccccbjshhdshsabjjbhsdbbbbbhajsdjasbosjahhchhshcbdsrbjbbdasjrsbshosschcbabbjasdccarc
chrbcb8bascjebhrhhhhahrsbcahcsrbaasebjjjbhcasaccaccccjhcchhjsjsebeajahhchebcbcsjhfbcjsjhjrabssjhbsdhharachshhsbcbcaha8cjhacehsbd
fdarcscibjfhaidbhjbrcoaihsah0hseccrahbcrisccsjjjjdrcssccschirrasccaaaiashhccbhaadashsbbsscsjacabcrdachcrbcacsaccjsbahaabhccbbhbb
jsbaaadahcbddasbsssshsbcijhsjcefhhsdarjrcsbhbhaahbbbjrsjbssrarcdadhchasjsdabajcbheabbccsrbha0crsaccshcbhjscsscababchh0jrshhfasac
echdjcjsaceshdcbsrababhobcdafscdjjahsabbdcbbcrarrcrjccbjcjsobbhcebbcbobcssjbabhhcdcscaaccjcrhbhibccbbsjaihcbhfjhrcahshhasjbaaaia
sabhhhccsjacchahccccbcidodacrjdeescchbhcbcasashhsaaarbcaeacbhbjchcsbahcrcchahdjasdhaajjcsishfjbchhbcsbisrcjhcjhahabssfrbcasehchb
dbscajrcabdcscbacbhihasbajchecjcrr0dchaicjaajchcbebrcharjrc8disjdaaba8aadccahacsbcjcjhhdjrjshassabbaacrhosbasersbjhdcsshcraechoh
bhasssbbcfhbbshsjsjjajsc8chjhrcddhjbcssbabecaccschhhbiehdhjisirbabcdhsfdabshscrhccahhrrbcbcserijssajcaocdjrsjrshshahbebijhddejsa
eacbhrabdadjcbahjcsoshcahrbsdjhbcbfcbshcbahhrjejadhbbshbracccsccchhah0ehcjjdshbcacrcrsscrcrcshcaccahhsdhfcahcdbaidscjcasjbhdbs8s
ashcacaajesaasscrcrrhccbhbsrsbbccsrabccahadjhsbcjsssiodscshococahajcscechahshbbsjdhsssbabdjcdhorcchhjhhjcrhcrchscscsaaihrsccdreb
dhjcsbhachcdjahscbcacsjhsbaccrsaciebacsbahssbrdrhccdaesibhbbbcjbbsbhefdscrrcbhajhbsbbcabbbdjesjhbbhssccsejhsjchhcccbhehhcascahac
hcshhjhhrdfhhccjbjbbsbcabacbcaabbcbhajddshcrscajacccj8cdbcsdjcbhshrdcadbshscsaicrcscbdbdacrjcsjbdjssrashbbsjbjscjafchhcsacbbcada
csrbchahbsbcbhscbajhjcrscihjcbchbodchjcahscheccssbbchdccisaaajeaacasdjcebsabdshrsacahjhaiacadchsaasscjbcdrscrbasbbbacdssbbcbbshj
sjcsscsshcessjjhiriicabhahjiahcaajishrcccsbbcjhrhbjjrcbcajccrbasbcccjhcabacjchosbbdjacdchbhcbcbicrccbhcsaacrirajrhejbabchhaabheh
bcbccshsacabascsahrsdjbcjosrjijsa8cbsrjhscjsdbbccacbschfdchhdrdhhbhccrbdachaccsbchehsrshchbhcjschhfcjcajccccdbbdaaahbcadaajaacss
hrccabccsbdccsrsscbbchashsrchsbhhrhbscbbjcaijssssarbbjabhhjcaahcabjbrsbhahhrjs8cabcbhbcbsasbabahbbjjhsjchhjbohhabsdrahacsshhasdd
afbbbcsbhjhahcjchaccccidrscbrhrchfbacbdbcjrccaabjhbdabsecdsscbcbsadjbsachjshbjaibsdscbcsjddsbbcjdseasbhjbjabcdachhbsabhchhrhhjcc
sbbjhajcaacjjbbccbaabbhcscbjscassbsacedarjhsrcccchbaihhassdbhhsjhdrabcascashrcjjhabasabachbahahsadccscrjssriasshaccbhshbccsshccc
heaabjcashshedrjbhjjbbdcbsjiescaeeahaicajcajbbhabsachfcdbcccbibachcaachbsracarhdacccccjcrcfceadschdhcasrardabchbdcachasbsscshrjj
hiacshrbhhbhracjjahhaasjdbircbhbcsch0dchhcscbdjjasbhosdhaccasscsscbhajhcbhcsbjrrshacbhaajdahshschcbbcjbracbohccshjbafccabjcccjbb
cdhhahjecbcsdcbrafrraacbhcrodbbhdehshobhbbhrbashachbsehcabjcabahacbhhjsabchbhbschabjbbrjbbesdcccbscbjhcbhbchabaacbhjshcabcbcsbhr
sohbcssassasbhcrrhsahhascaodjasajcjsfcbssbbaacbhhcas8ccbhjbhacjcdbishrahesjcidcbashbasbhhchscscdsbaajrbahja8sjjccrahejbdarjjbrac
bcsshsrdsajccbabhebbhhbasbb8caascdscbcasaasbahhhhjdacdsbhaabhahshbacsrchabsacccbshcbaahbiadccbbjacbarsjisibshahcbasrcsjhahajdifc
bsfajbchcchcisbbbschbahcbhrcahchrjhcebacaaahhbassshchjbasrashhrjcaocabhsdcrjocbihcsbhcabsbschcjccahhbbahsrhacrrjfbhsdrachdbraacb
cbccscacchajbahisdiissahaaiabhhcdccjajhhhhcihescsrcaacdachhashscsahbcbjahachbbjacsbahhsaohcjbaarejahscrocoacshdbahfcjhrshshacceb
acehhajsjjscbcaiicjsahsjacsbhejscasjdahjhhhseahcacsbsaahcbhhssbbdh8hhishcjbrabao0acasjhacacbacccahssasasbhshjbbaehsccbhbbcahhhba
bahhcjebbbhsahscccoocccshbshassjcbddhrssessocdcbcbbhhbchbssdcccjsasajihcsfjsaarhjcchssehssbbabebdehscjb8jchjcscahsedrsscscshbbda
hhdsscrcascbajhobcdchscrhbcasdrcjhchchshssscdhsahjhachcschsscchacs0ssccsbrishdhcfhjharsdjbjahbbbhdcchchcascsrichdscjbisaabhcsfah
ahshbrdaaasccscdjb8cjjbcsacshdsrbaccsbcadcc8bcjajiassabsacccjbjrchchbbsbcehahhccebbsacdscaaahadicdscjas0rjbrjcchscdcaccbajcsaach
dscchbhcccjahrbsabcdacjbsajhbcbhrsjsbscscccbchcdshshfsbcbsacjjshbcfacbjcabbcccsbesrshaccdarbsaaescjcsjsjhcjcrobsccjraobhhasbcehs
hccsabcbhhcbbcccha0bdaajchjcsccbahbbcijhcjj0abrdrohcchachbebrarbjsjsaacajdshssjbdaachscchhbhshcobccarhcdbrahajbsdccbhhjehrjchhbs
ccbjsasbbbahssachabchjrbcarsabisbccsbcjcjjeabsjccsbbecajachjraccejhhjarjccabbbcadcbcshbbchhacahdcbcbcrcrsjhjbbacbjbchaasshaajdsc
scjchdbassjadsbbshhachhahsrjcbjchsaaboacbrrfhabcarsaechcsadachahrcrchejdrccsccracchjscbcscasssbbabbhbsjcbhhdhraccbbassrdscjjssac
bsarchcaaahscchjshabsrhadhbshadcijbcajhjrbdhbcrbjcaadjhrdjsrbhjbdrbsrhaabjhaaajhcjihcsaabschjhscjajahdadchsrhaadarabahhbcshhrccj
cbrjscahccrhccaacsshbsshscbrdarjschha8hbabbcshibhcsddbcbchchjshsdhhbsdrccbhcdjhhbbsdcbabcbhahcaahbasicrbashcsbhjbaahcchccjrrcchj
achhjsjhhhscjjsbcscccbchcsbcbhcjrrajhrsrfacsabbarbhhcrsbcrbbisrachacbahhacshhhasbrosbchhacbddsbbrhrhschcsscbshhchbdahbsascesbbjr
jabrcbhsjbbcbbehjccsaccscbbbchbrcjssh0baheibcshasdcccabacsbsbccacssaccbbjbsjcasscaccaahahashsjhhcahchjbahcsecisrahhsjhbbbabbjaaa
hjssrbcsbscjrrcaccbbjhbabcajasbrbchrabcaehbchaaabacsbbcibbaaccbhbshjihsscbcssshcab8cabeshbacccaabsrscbsbcchicdsbshchsachcjdciarh
rhjajascrascaaddrcjhhcbejaasbscbdfccscahsdeajashccjbbhahbcacajbhbcchjbaaraccbhhdbhjbhhshshdscrscbhscscahsjcdjocbhhscrsaaahiidhhh
secdbabcaajsbhjhbjfarsahajhdbcabajsbhajhdeajshhhahbcdicbdddhjccsacsfhsdcbajfcdshhi0fhadcsaebbjhhacscjacajbsojccadsbccbjsjrcjohcs
bsrhrhcjbbcbbhcccbcsabadbhhbac0hcejjbdhaacdhrhcsjbhabshsebhjhrasajjssahhbhhbasscascasscacsccjbcbaccbabhscrjcr8jasscjhchhhsohcsbs
cdjcchajbhrcisbsarehhhhshracajhrhraasacscdcrasssbsajcbjacccsrbbchaceshcjahrejccsahfeshcjahdaacbshbcjradhraccrbahccadjasahbbd8sjc

