pico-8 cartridge // http://www.pico-8.com
version 34
__lua__
-- bad plastic
-- alexthescott 
-- 21/1/1

-- new seed every day of the year 
srand(31*stat(81)+stat(82)) 

p1={2,136,8,142,143,10,135,7}
p2={129,1,140,12,15,143,14,7}
p3={129,131,3,139,11,138,135,7}
p4={130,141,136,137,142,143,15,135}
p5={129,1,131,141,140,13,6,7}
p6={128,130,132,4,137,142,9,10}
p7={128,133,141,5,13,6,15,7}
p8={1,131,3,139,9,10,8,14}
p9={128,130,133,134,15,14,142,7}
p10={130,136,8,137,13,140,12,7}
 
p={p1,p2,p3,p4,p5,p6,p7,p8,p9,p10}
c=rnd(p)
pal(c,1)

function forward()
	v=c[1]
	del(c,v)
	c[#c+1]=v
	pal(c,1)
end

function dist(p1,p2)
	return sqrt((p1.x-p2.x)^2+(p1.y-p2.y)^2)
end

function still_r(p)
	return osc*3.2<(sin(p.x/(osc_off2*100))+cos(clock/6+p.y/(osc_off1*100))-sin(p.x/(osc_off1*200)))
end

function still_l(p)
	return osc_n/2-0.25>cos(p.x/(20+osc_off1*100))+sin(p.y/(20+osc_off2*64)-clock/10)
end

function hill(p)
	return sin(p.x/(osc_off1*100)+clock/2)+cos(p.y/(osc_off2*100))<osc/2
end

function dither_line(p)
	return cos(p.y/osc_off1*32-clock/3)+sin(p.x/osc_off2*32-clock/1.5)>0.5+osc_n/2
end

function seltzer(p)
	return osc_n-0.25>cos(p.x/(osc_off1*128)+clock/4)+sin(p.y/(osc_off2*128)-clock/6)
end

function seltzer_slow(p)
	return osc_n-0.25>sin(p.x/(osc_off1*64)+clock/4)+cos(p.y/(osc_off2*32)-clock/12)
end

function c_circ_fuzz(p)
	return rnd()*64*((1+osc)/2)>=dist(p,{x=64,y=64})
end

function c_circ(p)
	return 64*((1+osc)/2)>=dist(p,{x=64,y=64})
end

function c_circ_hori(p)
	if (p.y%2==0) return false
	return 64*((1+osc*2)/2)>=dist(p,{x=64,y=64})
end

function c_circ_vert(p)
	if (p.x%2==0) return false
	return 64*((1+osc*2)/2)>=dist(p,{x=64,y=64})
end

function c_circ_vert_s(p)
	slant=p.x*osc_n
	d=dist(p,{x=64,y=64})
	return (slant>=32 and slant<=40) or d>=osc_n*50
end

function c_circ_hori_s(p)
	slant=p.y*osc_n
	d=dist(p,{x=64,y=64})
	return (slant>=32 and slant<=40) or d>=osc_n*50
end

function c_square(p)
	return abs(p.x-64)<osc_n*64 and abs(p.y-64)<osc_n*64
end

function c_square_hori(p)
	return p.y%3!=0 and abs(p.x-64)<osc_n*64 and abs(p.y-64)<osc_n*64
end

function c_square_vert(p)
	return p.x%3!=0 and abs(p.x-64)<osc_n*64 and abs(p.y-64)<osc_n*64
end

for i=1,rnd()*16 do
	forward()
end

clock=0
osc=sin(clock)+sin(clock/2)
osc_n=((osc+1)/2)
osc_off1=(2+rnd(8))\1
osc_off2=(2+rnd(8))\1
line_dir=(rnd(2)\1)
c_cur=rnd(9)\1
plasmas={}
plasmas_weight={}
plasmas_count=6
for i=1,plasmas_count do
	plasmas[i]=true
	plasmas_weight[i]=1
end
-- rm n plasmas
for i=1,plasmas_count-4 do
	rm_i=1+rnd(plasmas_count)\1
	while plasmas[rm_i]==false do
		rm_i=1+rnd(plasmas_count)\1
	end
	plasmas[rm_i]=false
end
-- set two weights to half
for i=1,plasmas_count-3 do
	wh_i=1+rnd(plasmas_count)\1
	while plasmas[wh_i]==false do
		wh_i=1+rnd(plasmas_count)\1
	end
	plasmas_weight[wh_i]=0.5
end

dc_max=tonum(split(stat(6)," ")[2])
_set_fps(60)
cls(3)
::♥::
	for i=0,268 do
		local x=rnd(128)\1
		local y=rnd(128)\1
		local p={x=x,y=y}
		local v=1
		if (c_cur==0 and c_circ_hori(p)) or
			(c_cur==1 and c_circ_vert(p)) or
			(c_cur==2 and c_circ(p)) or 
			(c_cur==3 and c_circ_vert_s(p)) or
			(c_cur==4 and c_circ_hori_s(p)) or
			(c_cur==5 and c_circ_fuzz(p)) or 
			(c_cur==6 and c_square(p)) or 
			(c_cur==7 and c_square_hori(p)) or
			(c_cur==8 and c_square_vert(p)) then
				v+=3
		end
		if(plasmas[1] and still_l(p))v+=plasmas_weight[1]
		if(plasmas[2] and still_r(p))v+=plasmas_weight[2]
		if(plasmas[3] and dither_line(p))v+=plasmas_weight[3]
		if(plasmas[4] and seltzer(p))v+=plasmas_weight[4]
		if(plasmas[5] and seltzer_slow(p))v+=plasmas_weight[5]
		if(plasmas[6] and hill(p))v+=plasmas_weight[6]
		pset(x,y,v)
	end
	clock+=0.0008
	osc=sin(clock)
	osc+=(sin(clock/2)/2)*sin(clock/osc_off1)
	osc+=(sin(clock/2)/2)*sin(clock/osc_off2)
	osc/=3
	osc_n=((osc+1)/2)
	
	if btn(❎) or btn(🅾️) then
		--pass
	else
		flip()
	end

goto ♥
__gfx__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiiiiittiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiininnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiittttttitiittttiitiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiipiiiiiiipiiipiiipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiitiiiiiiiiiiiiiiipiiipipiiiiipipiiiiiiiiiiiiiiiiiiiiiiiiitttttttttitttiiiiiiniiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiiiipipipipiiipipipipipiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiinininnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiitiiiiitiiiiiitiiiiiiiipiiiiiiipipipiptptpipipipiptpipiiiiiiiitiiiiiiiiiiiiiiiitiiiiiiiiiniiinnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiipipipipipipipipipipipiptpiiiptpitipiiipipiiiiiiiiiiiiiiiiiiiiinnnninnnnnnnnnnnnnn
iiiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiiiiiipipipiiipipipitiiipipitiiipipipiiipipiiiiiiiiiiiiiiiiiiiiiinninnnnnnnnnnnnnnn
iiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiptpipipipipipipipipipipipipipipipiiipipiiiptiiiittttttttittttttiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipipiiipipipipitipipipipipipipipipipipipipipiiiiipipiiipiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnn
iititiiiiiiiiiiiiiiitiiiiiitiiiiiiiitpiiipipipipipiiipipipipipipipipiiipipipitipipipiptuiuiutiititttttittttttiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipiptpipipipipipipipipipipipipipipipipipipiiipiiipipipipiiiiipiiiiiiiiiiiiniiinnnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiipipipipipiitpipipipiiipipipipiiipipipipipipipipipiiipipiiipipipiiiiiiiiiiiniininnnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiitiiiiiiiiiiiiiiipipipipipipipiiipipipipipipipipipipipipipipipipipipiptpipipiiipiiiiiiiiiiinnnnnnnnnnninnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiitiipiiipipipipipipipipipipipipipipipipipipipipipipipipiiipipipipiiipipiiiptiiiiiiinninnnnnnnnnnnnnnnnn
iitiiiiiiiiiiiiiiiiiiiiiiiipiiiiipiiipipipipipipipipipipipipipipipitipipipipipipipiptutuiuiutututututttttttttttitiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipiiipipipipipipiptpipitipipipipipipipipipipipipipipipipiptpipipipiiipiiiiiinninnnnnnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiiiiiiiipipipiiipipipipipipipipipipipipipipipipipipiptpipipipipipipiuiutututitututuittttttttiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiipipipipipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipiiiiinininnnnnnnnnnnnnnn
iiiiiiiiiiiiitiiiitiiiiiipipipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiiiiitnninnnnnnnnnnnnn
iiiiiiiiiiiiiiiiiiiiipiiipipipiiipipipiiipipipipipipipipipititipipipipipiptpipipipipipipipipipipiiipipipiiipiiinntntnnnnnnninnnn
iiiiiiiiitiiiiiiiiiiipipipitipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiioinnnnninnnnnnnnnnn
iitiiiiiiiiiiiiiiiiiiiipitipiiipipipiiipipipipipipipipipipipipipipipipipipipiptpiptutuittututututututututututttttiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiipipttiptpipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipitipipiptpipipiiiiiiipioninnninnnnnnnnnn
iiiiiiiiiiiiitiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptptptptutptptptutututututututttututtitiiitiiiiiiiiii
iiiiiiiiiiiiiiiiiiipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiinnnnnnnnnnnnnn
iiiiiiiiiiiiiiiitpiiipipipiptpipipipipipipipipipipipipitipipipipipipitipipipipipipipipipipipipipipipipipipipipioinininnnnnnnnnnn
iiiiiiiiiiiiiiipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiuipiiipionnnnttnnninnnn
iiiiiiiiiiiiiiipipipipipipipipipitipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipnnninnnnnnnnnn
iiiiiiiiiiiiipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipiptutuiututuiututututptutututututututututuitttiiiiiiiiii
iiiiiiiiiiiiipiiipipiiipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipipipipipipipipipipipipipipipiiipiiininnnnnnnnn
iiittiiiiiipiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptuiuipiutptutututututuiutututututttutututpttiiitiiiiii
iiiiiiiiiiiiitipiiipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipninnninnnnnn
iiiiiiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipipipiiipiiiitpipniinininnnnn
iiiiiitiiiiiiiipipipipipiptpipipipitipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipiuipiptpipitipipipipintninnnnn
iiiiiitiiiiiipipipipipipipipipipitiptptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipipipipiininnnnnn
iiiiitiiipiiipipitipipipipttipipipipipipipipipipipipipipipipipipipiptptptutututututututututptptututututututututututututttiiiiiit
itiiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipiiiiiiniin
iiiiiiitipiiipiiipipipipitipipipipipipipipipipipipiptpipipipipipipipipiuiptutptutptuiuiutututptutututututututututuouttttittitiii
tiiiiiitipiptpiiipipipipipipipipiptpipipipipipipipipipipipipipipipiuipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiinn
iiiitiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptuipipipipipipipipipipipipipipipipipipiiipipipiiiiiininn
iiiiiiiiitipipipiiipipipipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipiuiuipipipipipipiuiptptpiptptpipipttitiiiitiii
iiiiiiiiipipiiipipipipipipipipipiuipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipiiipiiiinn
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipiutptuiptutptutpiututututututututptututututututututututttttutttttt
iiiiiiiiipipipiiipipipipipipipipipipipipiuipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipiiiiii
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipipiptpipiptuipiptutututututptututututututututututututututututututututotttttt
iiiiiitpipipipitiptpipipipipipipiptptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptiitipipiiiiii
iiiiiiiiiiipipipipipipipipipipipipipipipiptpipipitipipipipipipipipipipipipipipipipipipipipipipipipiptpipipiiipipipiiipipipiiiiii
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptptpipipipipipipipitipitipittiii
iiiiipiiipipipipipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipiiipiiii
iiiiipipipipipipipipipipipipipipipipipipipipipipipipipiptuipipiutptututututututututututututututututututututututututututututttttt
iiiitpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiii
iiiiipipipipipiptpipipipipipipipipipipipipipipipipipipipiututututuiutuiutututututututututututututututututututututututututututttt
iiiiitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiii
iiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipii
tiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipiuipipipiuiuipipipipipiptptuipipipitipiiii
iiiiipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipiiii
iiipiiiiipipiptpipipipipipipipipipipipipipipipipipipipiptutptututututututuiptututututututututututututututututututututttututttttt
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiii
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipiutptututptuiptptututututututututututututututututututututututututututututttt
iiiiiptpipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipii
iiiiipiiipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipiiii
iiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipiuipipipipipipipipiptpipiiii
iiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiii
iiipipipiiipipipipipipipipipipipipipipipipipipipiutptptutptptptutpiutututututututututututututututututututututututututututututttt
iiiiipipipipipipipipipipitipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipipipipipipiiipiiii
iiipipipipipipipipipipipipipipipipipipipipipiptutptututptututututututututututututututututututututututututututututttutututttttttt
tiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipii
iiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipiiiiii
iiipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiuipipipiutpipipipiuiutpiuiutpipitiiiiti
iiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipii
iiipipipipipipipipipipipipipipipipipipipipiptpipiututuiutututututututututututututututututututututututututututututututututututttt
iiiiiiipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipipipipii
iiipipipiiipipiiipipipipipipipipipipiptpipiutututuiututututptututututututututututututututututututututututututututttututttututttt
iiiitpipipipipipipipipitiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiii
iiiiiiipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipipipipipipitipipiiii
itiiipipipipipipipipipipipipipipipipipipipipipipiuipipipipipiuipiptpipipipipipiptpipipipiuipiuipipipipipipipipipiptpipipipipiiti
iiiiipipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipiiii
iiiiiiipipipipipipipipipipipipipiptutptptptutututututututututututututututututututututututututututututututututututututututututttt
iiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipiiipipiiipipipipiiiiii
iiiiiiipiiipiiipipiiipipipipipiuiptuiptpiututututptutututututututututututututututututututututututututututututuoututututututttttt
iiiiiiipipipipipipipiiiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiii
iiiiiiiiipipipipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiuipipipipipitipipipipiiiiiiii
iiiiiiipiiiiipipipipipipipipipipipipipipipipipipipipiptpipiuipiutpipipipiuipipiptpiptpipiptpipipipipipipipipipipipipiptpipiiiiii
iiiiiiipipipipipipipiiipipipipipipipipipipipipiuipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipiiiiipiiiiiiiiii
iiiiiiiiipipipipipipipipipipiuiuiitutututututututututututututututututututututututututututututututututututututututututttttttttttt
iitiiiipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipiiipiiiiiiii
iiiiiiiiipipipipipipipipiptuiptututututututututuiututututututututututututututututututututututututututututututututututututttttttt
iiiiiiiiipipiptpiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipipiiiiiiiiii
iiiiiiiiipipiiipipipipipipipipipipipipipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiiiiii
iitiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiuipipipipipipipipiptpipipipipipittpipipipipiiipiiiitiit
iiiiiiiiipipiiipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipiiiiiiiiii
iiiiitiiiiipipipipipipiptutututututututututututututututututututututututututututututotututututututututututututttututututttttttttt
iiiiiiiiiiipiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitiiiiiiiiii
iiiiiiiiiiipipipiiipiutututpiutptutuiutututuiututututututututututututututututututututututututututututututututttutttututttttttttt
iiiiiiiiiiiiiiipipiiipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipioipipipipipipipipipipipiiiiiiiiiiii
iiiiiiiiiiiiiiiiipitipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipitipipipipipipipipipipipiiipiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiipipipitipipipipipipipipipipipipipiuipitipiptuiptpipipipiuipipipipiuiuipipiuipipipttiuiutpipiptpiiiiiiiitiiiii
iiiiiiiiiiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipipipipipipipiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiipiptuiptututuiutitutututututututututututututututututututututututututututttutututututttututututututttttttttttttttt
iiiiiiiiiiiiiiipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiiiiiiiiii
iiiiiiiiiiiiitiituiutitututututututututututututututututututututututututututututututututututututututututututututttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiipipiiipipipipipipipipiiipipipipipipipipipipipipipipipiiipipipipipipipipipipipipipiiiiipiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiipiiipipipipipipipipipipipipipipipiptpipipipipipipipipipipipipipipipipipipipipipipipipipipioipiiitiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiipipiiipipiptiipiptpipiiipiuipiuipipipipipipipipiuipipipipipiptpipipipiuipttiuiptpipipitiitiiiiiiiiiiiiiiiit
iiiiiiiiiiiiiiiiiiiiiiipipipipipipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiittttiittttttutututttutututututututututututututututututututututututututututututututututttutututttttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiipiiiiiiiiitiiiiiiiiiiii
iiiiiiiititttittittiittttttutttututututututututututututututututttutututututututttutututututututututututttutttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipipipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipiiipipiiipipiiiiiiiiiiiiiiiiiiiitiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipitipipiptpiptptpipipipipipiuiptpiptptpipiptpipipiptuiptpipipipiiipipipiiitittiititiiititiiitiiit
iiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipipipipipipipipipipipipipiiipipipipipipipipipipipipipipiiiiipipipiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iitiitttttittttttttttttttttttutttttutttututututututututututututututututututututututututttututututttttttttttttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipipipipipipipipipipipipipipipipipipipipipipipipipipipiiipipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
ittittittttttttttttttttttttttttttitutututututututututututututututututututututututututututututttttttttttttttttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiipipipipipipipipipipipipipipipipipipiiipipipiiipipipiiipipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiiiipipiiipipipipipipiiipipipipipipipipipipiiipipipiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiittiiiiiiiiiiiipipiiipipipipipiptoipipipipipipipipipitipipipipipipipiiiiitiittitiiiiiiiiiiiiitiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipipiiipiiiiipipipipipipipipipiiipiiipiiipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iittiitttttttttttttttttttttttttttttttttttttttutututttutttttutututututttututttttttttttututttttotttttttttttttttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipiiipiiipipipipipipipipipipiiiiiiipiiiiiiiiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiii
ittittttttttttttttttittttttttttttttttttttttttttttutttututttutututttttutttttutttututttttttttttttttttttttttttttttttttttttttttttttt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipipipiiiptpipiiiiipipipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiipiiipipiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
iiiiiiiiiiittiiiititiiititiiiiiiiiiiiiiiiiiiiiiitiittiiiiitittiiiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiitiiiitititititiiiiiiiiiiiiiiiitt
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

